"""AutoIC AI engine.

All Anthropic Claude API calls run inside `AIWorker(QThread)` — the Qt main
thread is never blocked. `AIEngine` holds the SDK client, model, and system
prompts and exposes one method per pipeline stage. Each method returns the
spawned worker; callers connect to its `progress / response_ready / error`
signals.

Defensive parsing:
- JSON tasks: extract first balanced ``{...}`` block, validate via ``json.loads``.
- HDL/SPICE tasks: extract the first triple-backtick code block; fall back to
  the entire response if no fence is present.
- Failures (API errors, parse errors) trigger up to 3 exponential-backoff
  retries (1s → 2s → 4s).
"""

from __future__ import annotations

import json
import logging
import re
import time
import traceback
from dataclasses import dataclass
from typing import Any, Callable, Optional

from PyQt6.QtCore import QObject, QThread, pyqtSignal

from .ai_provider import (
    AIProvider, AIProviderConfig, AIProviderError, AIProviderFactory,
    PROVIDER_ANTHROPIC, DEFAULT_MODELS,
)
from .ai_log import AILogBus

log = logging.getLogger("autoic.ai")


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------
class AIEngineError(Exception):
    """Raised when the AI engine cannot complete a request."""


class AIParseError(AIEngineError):
    """Raised when the model output cannot be parsed."""


# ---------------------------------------------------------------------------
# System prompts
# ---------------------------------------------------------------------------
SYS_SPEC = """You are a senior IC design engineer. The user describes an integrated circuit in
natural language. Output a STRICT JSON object describing a complete design specification.

Output format (no prose, no markdown, JSON only):
{
  "name": "string",
  "ic_type": "digital" | "analog" | "mixed" | "power",
  "technology_node": "string e.g. 180nm",
  "supply_voltage": <number, volts>,
  "input_pins": [ {"name":"...","direction":"input","voltage_level":"...","pin_type":"signal|clock|power|ground"} ],
  "output_pins": [ {"name":"...","direction":"output","voltage_level":"...","pin_type":"signal|power|ground"} ],
  "functional_description": "string",
  "performance_targets": { "key": "value" },
  "constraints": [ "string" ]
}
Use realistic engineering defaults if the user omits details. Output JSON only."""

SYS_DESIGN = """You are a senior IC design engineer. Given an IC specification, output a STRICT
JSON object describing the full implementation.

Output format (JSON only):
{
  "components": [
    {"id":"U1","type":"NAND2|AND2|OR2|NOT|XOR2|DFF|MUX2|RES|CAP|IND|NMOS|PMOS|BJT|OPAMP|DIODE|VSRC|GND|VDD",
     "value":"string e.g. 10k, 1uF, W=2u L=180n",
     "model":"string",
     "pins":["A","B","Y"],
     "rationale":"why this component & value"}
  ],
  "nets": [
    {"id":"N1","name":"clk","connected_pins":["U1.CLK","U2.CLK"],"net_type":"clock|signal|power|ground"}
  ],
  "rationale": { "topology": "string", "key_decisions": ["..."] },
  "timing_estimates": { "max_delay_ns": <num>, "fmax_mhz": <num> },
  "power_estimate_mw": <num>,
  "area_estimate_um2": <num>
}

Rules:
- Always include VDD and GND nets, plus a VDD source component and at least one GND reference.
- For digital: components must be standard cells (gates / FFs / muxes).
- For analog: provide R/C/L/MOSFET/BJT/op-amp/diode with realistic values.
- For power: include FETs, inductors, caps, comparator, error amp, switching freq, duty cycle.
- pin connections use "<componentId>.<pinName>" notation; every component pin must appear in exactly one net.
Output JSON only."""

SYS_VERILOG = """You are a Verilog RTL expert. Output a complete synthesizable Verilog module
that implements the supplied IC design. Constraints:
- Yosys-parseable (no SystemVerilog-only syntax).
- Header comment block with IC name, "Generated by AutoIC", ISO timestamp, spec summary.
- Declare `module` ... `endmodule` with all ports from the spec.
- Use `assign` and `always @(*)` / `always @(posedge clk)` blocks as needed.
- For analog/power ICs: produce a behavioral model using `real` signals
  inside `always @*` blocks, and add a `// behavioral` comment marker.
Output ONLY the Verilog code wrapped in a single ```verilog ... ``` fence."""

SYS_SPICE = """You are a SPICE netlist expert. Output a complete ngspice-compatible netlist for
the supplied IC design. Constraints:
- First line: ``.title <name>``.
- Component lines using R/C/L/M/Q/X.
- ``.model`` statements for any custom MOSFET/BJT models.
- Include ``.op`` always; add ``.tran`` for digital/power, ``.ac`` for analog.
- VDD must be a voltage source on net VDD; ground node is ``0`` (or GND aliased to 0).
- No floating nets; every node must be referenced by at least one component.
- End with ``.end``.
Output ONLY the SPICE netlist wrapped in a single ```spice ... ``` fence."""

SYS_DRC = """You are a senior IC verification engineer performing AI-judged design rule checks
on top of a programmatic DRC pass. Output STRICT JSON only:
{
  "violations": [
    {"rule_id":"AI-001","severity":"PASS|WARN|FAIL","component_ref":"U3","message":"...","suggested_fix":"..."}
  ]
}
Focus on biasing validity, stability margin, clock-domain-crossing
synchronization, supply decoupling adequacy, and topology sanity. Output JSON only."""

SYS_AUTOFIX = """You are a senior IC designer fixing DRC violations. Given the current ICDesign
JSON and a list of violations, output a corrected ICDesign JSON in the SAME schema as the input.
Make the minimal edits needed to resolve every FAIL and as many WARNs as possible.
Output JSON only."""

SYS_CHAT = """You are AutoIC, an expert IC design assistant embedded in a desktop EDA tool.
You may modify the user's current design. If the user asks for a design change, return a
JSON object: {"message":"plain explanation","design_patch": <full updated ICDesign JSON or null>}.
For pure questions, set design_patch to null. Output JSON only."""


# ---------------------------------------------------------------------------
# AIWorker
# ---------------------------------------------------------------------------
@dataclass
class _Task:
    fn: Callable[..., Any]
    args: tuple
    kwargs: dict
    label: str


class AIWorker(QThread):
    """Run an arbitrary AI engine call on a background thread."""

    response_ready = pyqtSignal(object)   # parsed result (dict / str)
    error = pyqtSignal(str)
    progress = pyqtSignal(str)
    finished_ok = pyqtSignal()
    cancelled = pyqtSignal()

    def __init__(self, task: _Task, provider: "AIProvider",
                 parent: Optional[QObject] = None) -> None:
        super().__init__(parent)
        self._task = task
        self._provider = provider
        self._cancel_requested: bool = False

    def cancel(self) -> None:
        """Request a forceful abort of the current AI call."""
        self._cancel_requested = True
        self.requestInterruption()
        try:
            self._provider.cancel()
        except Exception:  # noqa: BLE001
            log.exception("provider.cancel() failed")
        AILogBus.instance().warn(
            "cancel", f"User cancelled task: {self._task.label}")

    @property
    def is_cancelled(self) -> bool:
        return self._cancel_requested

    def run(self) -> None:  # noqa: D401
        try:
            self.progress.emit(f"{self._task.label} — starting")
            AILogBus.instance().info("task", f"▶ {self._task.label}")
            result = self._task.fn(
                *self._task.args,
                _progress=self.progress.emit,
                _is_cancelled=lambda: self._cancel_requested,
                **self._task.kwargs,
            )
            if self._cancel_requested:
                AILogBus.instance().warn(
                    "cancel", f"● {self._task.label} cancelled")
                self.cancelled.emit()
                return
            self.progress.emit(f"{self._task.label} — done")
            AILogBus.instance().info("task", f"✔ {self._task.label} done")
            self.response_ready.emit(result)
            self.finished_ok.emit()
        except Exception as exc:  # noqa: BLE001
            if self._cancel_requested:
                AILogBus.instance().warn(
                    "cancel", f"● {self._task.label} cancelled")
                self.cancelled.emit()
                return
            log.error("AIWorker [%s] failed: %s\n%s",
                      self._task.label, exc, traceback.format_exc())
            AILogBus.instance().error(
                "task", f"✕ {self._task.label}: {exc}")
            self.error.emit(f"{self._task.label}: {exc}")


# ---------------------------------------------------------------------------
# AIEngine
# ---------------------------------------------------------------------------
class AIEngine(QObject):
    """High-level wrapper around the Anthropic SDK.

    Each public method spawns and starts an `AIWorker` and returns it so the
    caller can connect to its signals. The worker auto-deletes when finished.
    """

    DEFAULT_MODEL = DEFAULT_MODELS[PROVIDER_ANTHROPIC]
    MAX_RETRIES = 3
    BACKOFF_BASE = 1.0  # seconds

    def __init__(
        self,
        api_key: str = "",
        model: Optional[str] = None,
        parent: Optional[QObject] = None,
        provider_config: Optional[AIProviderConfig] = None,
    ) -> None:
        super().__init__(parent)
        if provider_config is None:
            provider_config = AIProviderConfig(
                provider=PROVIDER_ANTHROPIC,
                api_key=api_key or "",
                model=model or self.DEFAULT_MODEL,
            )
        self._config: AIProviderConfig = provider_config
        self._provider: AIProvider = AIProviderFactory.create(self._config)
        self._workers: list[AIWorker] = []

    # -- configuration ----------------------------------------------------
    def set_api_key(self, key: str) -> None:
        self._config.api_key = key or ""
        self._provider = AIProviderFactory.create(self._config)

    def set_model(self, model: str) -> None:
        if model:
            self._config.model = model
        self._provider = AIProviderFactory.create(self._config)

    def set_provider(self, config: AIProviderConfig) -> None:
        """Hot-swap provider at runtime (called by Settings)."""
        self._config = config
        self._provider = AIProviderFactory.create(config)

    @property
    def config(self) -> AIProviderConfig:
        return self._config

    @property
    def provider(self) -> AIProvider:
        return self._provider

    @property
    def api_key(self) -> str:
        return self._config.api_key

    @property
    def model(self) -> str:
        return self._config.model

    def is_ready(self) -> bool:
        try:
            return bool(self._provider.health_check())
        except Exception:  # noqa: BLE001
            return False

    # -- core call --------------------------------------------------------
    def _call(self, system: str, user: str, *, max_tokens: int = 8000,
              temperature: float = 0.2,
              _progress: Callable[[str], None] | None = None,
              _is_cancelled: Callable[[], bool] | None = None) -> str:
        last_exc: Optional[Exception] = None
        # Reset any prior cancel flag before this call.
        try:
            self._provider.reset_cancel()
        except Exception:  # noqa: BLE001
            pass
        for attempt in range(1, self.MAX_RETRIES + 1):
            if _is_cancelled and _is_cancelled():
                raise AIEngineError("Cancelled by user")
            try:
                if _progress:
                    _progress(f"Calling {self._provider.name} ({self._config.model}) — attempt {attempt}")
                text = self._provider.complete(
                    system, user,
                    max_tokens=max_tokens, temperature=temperature,
                )
                if not text:
                    raise AIParseError("Empty response from model")
                return text
            except AIProviderError as e:
                if _is_cancelled and _is_cancelled():
                    raise AIEngineError("Cancelled by user") from e
                last_exc = e
                wait = self.BACKOFF_BASE * (2 ** (attempt - 1))
                log.warning("Provider error (attempt %d): %s — backoff %.1fs",
                            attempt, e, wait)
                if _progress:
                    _progress(f"Provider error, retrying in {wait:.1f}s")
                # Sleep in small slices so cancellation is responsive.
                slept = 0.0
                while slept < wait:
                    if _is_cancelled and _is_cancelled():
                        raise AIEngineError("Cancelled by user") from e
                    chunk = min(0.2, wait - slept)
                    time.sleep(chunk)
                    slept += chunk
            except Exception as e:  # noqa: BLE001
                last_exc = e
                log.exception("Unexpected AI call failure")
                break
        raise AIEngineError(f"AI call failed after {self.MAX_RETRIES} attempts: {last_exc}")

    # -- output extraction ------------------------------------------------
    @staticmethod
    def _extract_json(text: str) -> dict:
        """Best-effort extraction of the first balanced JSON object."""
        # Try fenced block first.
        m = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, flags=re.DOTALL)
        candidate = m.group(1) if m else None
        if candidate is None:
            # Scan for first balanced { ... } block.
            depth = 0
            start = -1
            for i, ch in enumerate(text):
                if ch == "{":
                    if depth == 0:
                        start = i
                    depth += 1
                elif ch == "}":
                    depth -= 1
                    if depth == 0 and start >= 0:
                        candidate = text[start: i + 1]
                        break
        if not candidate:
            raise AIParseError("No JSON object found in model response")
        try:
            return json.loads(candidate)
        except json.JSONDecodeError as e:
            raise AIParseError(f"Invalid JSON: {e}") from e

    @staticmethod
    def _extract_code(text: str, language: str) -> str:
        m = re.search(rf"```{language}\s*(.*?)```", text, flags=re.DOTALL | re.IGNORECASE)
        if m:
            return m.group(1).strip()
        m = re.search(r"```\w*\s*(.*?)```", text, flags=re.DOTALL)
        if m:
            return m.group(1).strip()
        return text.strip()

    def _retrying_json(self, system: str, user: str, *, label: str,
                       _progress: Callable[[str], None] | None = None,
                       _is_cancelled: Callable[[], bool] | None = None,
                       temperature: float = 0.2, max_tokens: int = 8000) -> dict:
        last: Exception | None = None
        for attempt in range(1, self.MAX_RETRIES + 1):
            if _is_cancelled and _is_cancelled():
                raise AIEngineError("Cancelled by user")
            text = self._call(system, user, _progress=_progress,
                              _is_cancelled=_is_cancelled,
                              temperature=temperature, max_tokens=max_tokens)
            try:
                return self._extract_json(text)
            except AIParseError as e:
                last = e
                if _progress:
                    _progress(f"{label}: parse error, retrying ({attempt}/{self.MAX_RETRIES})")
                time.sleep(self.BACKOFF_BASE * attempt)
        raise AIEngineError(f"{label}: could not parse JSON output: {last}")

    # -- task dispatch helper --------------------------------------------
    def _run(self, fn: Callable[..., Any], label: str, *args, **kwargs) -> AIWorker:
        worker = AIWorker(_Task(fn=fn, args=args, kwargs=kwargs, label=label),
                          provider=self._provider)
        # Keep a strong reference so the QThread isn't GC'd mid-flight.
        self._workers.append(worker)
        worker.finished.connect(lambda: self._workers.remove(worker) if worker in self._workers else None)
        worker.start()
        return worker

    # -- cancellation ----------------------------------------------------
    def cancel_all(self) -> int:
        """Forcefully cancel every in-flight AI worker.

        Returns the number of workers that were asked to cancel.
        """
        cancelled = 0
        for w in list(self._workers):
            try:
                if w.isRunning():
                    w.cancel()
                    cancelled += 1
            except Exception:  # noqa: BLE001
                log.exception("cancel_all: worker cancel failed")
        # Belt-and-braces: also flip the provider flag in case a worker
        # already moved past _provider.cancel() but is still in retry sleep.
        try:
            self._provider.cancel()
        except Exception:  # noqa: BLE001
            pass
        return cancelled

    @property
    def workers(self) -> list[AIWorker]:
        return list(self._workers)

    # -- public pipeline methods -----------------------------------------
    def generate_ic_spec(self, nl_input: str) -> AIWorker:
        def task(nl: str, *, _progress=None, _is_cancelled=None) -> dict:
            return self._retrying_json(
                SYS_SPEC,
                f"User request:\n{nl}\n\nReturn the JSON spec.",
                label="spec", _progress=_progress, _is_cancelled=_is_cancelled,
                temperature=0.2,
            )
        return self._run(task, "Generating IC spec", nl_input)

    def generate_design(self, spec: dict) -> AIWorker:
        def task(spec: dict, *, _progress=None, _is_cancelled=None) -> dict:
            return self._retrying_json(
                SYS_DESIGN,
                "IC specification:\n" + json.dumps(spec, indent=2)
                + "\n\nReturn the full design JSON.",
                label="design", _progress=_progress,
                _is_cancelled=_is_cancelled, temperature=0.2,
                max_tokens=12000,
            )
        return self._run(task, "Designing topology", spec)

    def generate_verilog(self, design: dict) -> AIWorker:
        def task(design: dict, *, _progress=None, _is_cancelled=None) -> str:
            text = self._call(
                SYS_VERILOG,
                "ICDesign JSON:\n" + json.dumps(design, indent=2),
                _progress=_progress, _is_cancelled=_is_cancelled,
                temperature=0.15, max_tokens=10000,
            )
            return self._extract_code(text, "verilog")
        return self._run(task, "Generating Verilog", design)

    def generate_spice(self, design: dict) -> AIWorker:
        def task(design: dict, *, _progress=None, _is_cancelled=None) -> str:
            text = self._call(
                SYS_SPICE,
                "ICDesign JSON:\n" + json.dumps(design, indent=2),
                _progress=_progress, _is_cancelled=_is_cancelled,
                temperature=0.15, max_tokens=10000,
            )
            return self._extract_code(text, "spice")
        return self._run(task, "Generating SPICE", design)

    def run_drc(self, design: dict, netlist: str) -> AIWorker:
        def task(design: dict, netlist: str, *, _progress=None, _is_cancelled=None) -> dict:
            return self._retrying_json(
                SYS_DRC,
                "ICDesign JSON:\n" + json.dumps(design, indent=2)
                + "\n\nSPICE netlist:\n" + netlist[:6000]
                + "\n\nReturn DRC violations JSON.",
                label="drc", _progress=_progress,
                _is_cancelled=_is_cancelled, temperature=0.2,
            )
        return self._run(task, "Running AI DRC", design, netlist)

    def auto_fix(self, design: dict, violations: list[dict]) -> AIWorker:
        def task(design: dict, violations: list[dict], *, _progress=None,
                 _is_cancelled=None) -> dict:
            return self._retrying_json(
                SYS_AUTOFIX,
                "Current ICDesign JSON:\n" + json.dumps(design, indent=2)
                + "\n\nViolations:\n" + json.dumps(violations, indent=2)
                + "\n\nReturn the corrected ICDesign JSON.",
                label="autofix", _progress=_progress,
                _is_cancelled=_is_cancelled, temperature=0.2,
                max_tokens=12000,
            )
        return self._run(task, "Auto-fixing DRC", design, violations)

    def chat_modify(self, current_design: dict | None, user_message: str) -> AIWorker:
        def task(design: dict | None, msg: str, *, _progress=None,
                 _is_cancelled=None) -> dict:
            payload = {
                "current_design": design,
                "user_message": msg,
            }
            return self._retrying_json(
                SYS_CHAT,
                json.dumps(payload, indent=2),
                label="chat", _progress=_progress,
                _is_cancelled=_is_cancelled, temperature=0.4,
                max_tokens=10000,
            )
        return self._run(task, "AI chat", current_design, user_message)
