"""Verilog generator.

Wraps the AI Verilog call with a deterministic post-processor: header banner,
balanced-parenthesis lint, and a fallback structural template if Claude is
unreachable.
"""

from __future__ import annotations

import datetime as _dt
import logging
import re
from typing import Optional

from .design_engine import ICDesign

log = logging.getLogger("autopcb.verilog")


class VerilogLintError(ValueError):
    pass


class VerilogGenerator:
    """Post-processes raw Claude Verilog output and provides a fallback template."""

    @staticmethod
    def banner(design: ICDesign) -> str:
        ts = _dt.datetime.now(_dt.timezone.utc).isoformat()
        spec = design.spec
        return (
            "// =============================================================\n"
            f"// Module: {spec.name}\n"
            "// Generated by AutoPCB — AI-powered IC design\n"
            f"// Timestamp (UTC): {ts}\n"
            f"// IC type: {spec.ic_type}\n"
            f"// Technology: {spec.technology_node}, Vdd = {spec.supply_voltage} V\n"
            f"// Description: {spec.functional_description}\n"
            "// =============================================================\n"
        )

    @classmethod
    def finalize(cls, design: ICDesign, raw_code: str) -> str:
        code = (raw_code or "").strip()
        # Strip any fenced wrappers Claude may leak through.
        code = re.sub(r"^```\w*\n?", "", code)
        code = re.sub(r"\n?```$", "", code)
        if "module" not in code or "endmodule" not in code:
            log.warning("Claude Verilog missing module/endmodule — substituting fallback")
            code = cls.fallback(design)
        cls.lint(code)
        return cls.banner(design) + "\n" + code.strip() + "\n"

    # -- fallback --------------------------------------------------------
    @classmethod
    def fallback(cls, design: ICDesign) -> str:
        spec = design.spec
        name = re.sub(r"[^A-Za-z0-9_]", "_", spec.name) or "autopcb_module"
        ports: list[str] = []
        decls: list[str] = []
        for p in spec.input_pins:
            if p.pin_type in ("power", "ground"):
                continue
            ports.append(p.name)
            decls.append(f"  input  wire {p.name};")
        for p in spec.output_pins:
            if p.pin_type in ("power", "ground"):
                continue
            ports.append(p.name)
            decls.append(f"  output wire {p.name};")
        port_list = ",\n  ".join(ports) if ports else ""
        body_lines: list[str] = []
        is_behavioral = spec.ic_type in ("analog", "power")
        if is_behavioral:
            body_lines.append("  // behavioral — analog/power IC behavioural model")
            for p in spec.output_pins:
                if p.pin_type in ("power", "ground"):
                    continue
                body_lines.append(f"  assign {p.name} = 1'b0; // placeholder behaviour")
        else:
            for p in spec.output_pins:
                if p.pin_type in ("power", "ground"):
                    continue
                body_lines.append(f"  assign {p.name} = 1'b0; // TODO connect real logic")
        body = "\n".join(body_lines) if body_lines else "  // no logic"
        return (
            f"module {name} (\n  {port_list}\n);\n"
            + "\n".join(decls)
            + "\n\n"
            + body
            + "\n\nendmodule\n"
        )

    # -- lint ------------------------------------------------------------
    @staticmethod
    def lint(code: str) -> None:
        if "module" not in code:
            raise VerilogLintError("missing 'module' keyword")
        if "endmodule" not in code:
            raise VerilogLintError("missing 'endmodule' keyword")
        opens = code.count("(")
        closes = code.count(")")
        if opens != closes:
            raise VerilogLintError(f"unbalanced parentheses ({opens} vs {closes})")
        opens_b = code.count("{")
        closes_b = code.count("}")
        if opens_b != closes_b:
            raise VerilogLintError(f"unbalanced braces ({opens_b} vs {closes_b})")

    # -- convenience -----------------------------------------------------
    def generate_offline(self, design: ICDesign) -> str:
        """Pure deterministic generation (no Claude). Useful for tests."""
        return self.banner(design) + "\n" + self.fallback(design)
